Interactive chart of headcount in UK Government departments
========================================================

```{r tidy = TRUE}
library(plyr)
# load data
RawDeptsFTE <- read.csv("~/Desktop/RawDeptsFTE.csv")

# get rid of fluff in colnames, making it suitable for reshape and googlevis
names(RawDeptsFTE) <- gsub("[.]","", names(RawDeptsFTE))
names(RawDeptsFTE) <- gsub("FTE","", names(RawDeptsFTE))
names(RawDeptsFTE) <- gsub("X","FTE", names(RawDeptsFTE))

DeptsFTE <- ddply(RawDeptsFTE, .(Dept,Whitehall), summarise,
                  sFTE2009Q1 = sum(FTE2009Q1,na.rm=TRUE),
                  sFTE2009Q2 = sum(FTE2009Q2,na.rm=TRUE),
                  sFTE2009Q3 = sum(FTE2009Q3,na.rm=TRUE),
                  sFTE2009Q4 = sum(FTE2009Q4,na.rm=TRUE),
                  sFTE2010Q1 = sum(FTE2010Q1,na.rm=TRUE),
                  sFTE2010Q2 = sum(FTE2010Q2,na.rm=TRUE),
                  sFTE2010Q3 = sum(FTE2010Q3,na.rm=TRUE),
                  sFTE2010Q4 = sum(FTE2010Q4,na.rm=TRUE),
                  sFTE2011Q1 = sum(FTE2011Q1,na.rm=TRUE),
                  sFTE2011Q2 = sum(FTE2011Q2,na.rm=TRUE),
                  sFTE2011Q3 = sum(FTE2011Q3,na.rm=TRUE),
                  sFTE2011Q4 = sum(FTE2011Q4,na.rm=TRUE),
                  sFTE2012Q1 = sum(FTE2012Q1,na.rm=TRUE),
                  sFTE2012Q2 = sum(FTE2012Q2,na.rm=TRUE)
                  )

# now convert to wide to create WH and NWH FTE vars for each

DeptsFTEwide <- reshape(DeptsFTE, idvar = "Dept",
                  timevar = "Whitehall", direction = "wide")

# make names manageable
names(DeptsFTEwide) <- gsub("sFTE","", names(DeptsFTEwide))
names(DeptsFTEwide) <- gsub(".Core Whitehall Depts.","WH", names(DeptsFTEwide))
names(DeptsFTEwide) <- gsub(".Non-Whitehall Civil Service","NWH", names(DeptsFTEwide))

# now convert to long
DeptsFTElong <- reshape(DeptsFTEwide, idvar = c("Dept"), 
                  varying = list(c(2:15),c(16:29)),
                  v.names = c("FTE_WH", "FTE_NWH"),
                  times = c("2009Q1","2009Q2","2009Q3","2009Q4",
                            "2010Q1","2010Q2","2010Q3","2010Q4",
                            "2011Q1","2011Q2","2011Q3","2011Q4",
                            "2012Q1","2012Q2"),
                  timevar = "Period",
                  direction = "long")

# Notes:
# yLambda: 0 is log, 1 is linear
# timeUnit: originally was _NOTHING
# playduration is in ms
# need to set xaxisoption to _NOTHING if showing bubble by default

```

```{r tidy=FALSE}

suppressPackageStartupMessages(library(googleVis))

Motion=gvisMotionChart(DeptsFTElong, idvar="Dept", timevar="Period",
                       options=list(
                       height=400, 
                       width=1000, 
                       state="{\"iconKeySettings\":[],\"stateVersion\":3,
                        \"time\":\"2010-07-01\",\"xAxisOption\":\"_ALPHABETICAL\",
                        \"playDuration\":4000,\"iconType\":\"VBAR\",
                        \"sizeOption\":\"_UNISIZE\",\"xZoomedDataMin\":null,
                        \"xZoomedIn\":false,
                        \"duration\":{\"multiplier\":1,\"timeUnit\":\"Q\"},
                        \"yZoomedDataMin\":null,
                        \"xLambda\":1,\"colorOption\":\"_NOTHING\",
                        \"nonSelectedAlpha\":0.4,
                        \"dimensions\":{\"iconDimensions\":[]},
                        \"yZoomedIn\":false,\"yAxisOption\":\"_NOTHING\",
                        \"yLambda\":0,\"yZoomedDataMax\":null,
                        \"showTrails\":true,\"xZoomedDataMax\":null};",
                       showSelectListComponent = 1,
                       showHeader=1,
                       showAdvancedPanel=1,
                       showChartButtons=1,
                       showXScalePicker=1,
                       showYScalePicker=1,
                       showXMetricPicker=1,
                       showYMetricPicker=1,
                       showSidePanel=1
                       ))
```


```{r results = "asis"}
print(Motion, "chart")
```
